### ISSUE TITLE
What can I do, if my app need to support Chinese?

### ISSUE THREAD

**Issue by Lemac** [leodennis/Android_GLES2.0_GUI#2]
RT

Best Regards

**Comment by leodennis** [comment]
I haven't actually tried chinese but if you have a chinese font it migth just work like other fonts:
 - Use The TextureFontAtlas tool to export the characters you need
 - Import the generated font atlases and font classes into the Android project

If that does not work you'll have to look for a different solution because I am specializing on the latin alphabet...

Good luck
Leo
